package com.example.biddutkarmakar.kaptainewcorrection;

import android.graphics.Typeface;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.Html;
import android.widget.TextView;

public class FishBioversityList3 extends AppCompatActivity {

    TextView tx1,tx2,tx3,tx4,tx5,tx6,tx7,tx8,tx9,tx10,tx11,tx12,tx13,tx14,tx15,tx16,tx17,tx18,tx19,tx20,tx21,tx22,tx23,tx24,tx25,tx26,tx27,tx28,tx29,tx30,tx31,tx32,tx33,tx34,tx35,tx36,tx37,tx38,tx39,tx40,tx41,tx42,tx43;
    TextView tx44,tx45,tx46,tx47,tx48,tx49,tx50,tx51,tx52,tx53,tx54,tx55,tx56,tx57,tx58,tx59,tx60;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_fish_bioversity_list3);

        String fontPath1 = "fonts/AdorshoLipi_20-07-2007.ttf";
        Typeface tf1 = Typeface.createFromAsset(getAssets(), fontPath1);

        ActionBar actionBar = getSupportActionBar();
        actionBar.setTitle(Html.fromHtml("<b> পরিবর্তনের ধারা   </b>"));

        tx1=(TextView)findViewById(R.id.text1);
        tx2=(TextView)findViewById(R.id.text2);
        tx3=(TextView)findViewById(R.id.text3);
        tx4=(TextView)findViewById(R.id.text4);
        tx5=(TextView)findViewById(R.id.text5);
        tx6=(TextView)findViewById(R.id.text6);
        tx7=(TextView)findViewById(R.id.text7);
        tx8=(TextView)findViewById(R.id.text8);
        tx9=(TextView)findViewById(R.id.text9);
        tx10=(TextView)findViewById(R.id.text10);
        tx11=(TextView)findViewById(R.id.text11);
        tx12=(TextView)findViewById(R.id.text12);
        tx13=(TextView)findViewById(R.id.text13);
        tx14=(TextView)findViewById(R.id.text14);
        tx15=(TextView)findViewById(R.id.text15);
        tx16=(TextView)findViewById(R.id.text16);
        tx17=(TextView)findViewById(R.id.text17);
        tx18=(TextView)findViewById(R.id.text18);
        tx19=(TextView)findViewById(R.id.text19);
        tx20=(TextView)findViewById(R.id.text20);
        tx21=(TextView)findViewById(R.id.text21);
        tx22=(TextView)findViewById(R.id.text22);
        tx23=(TextView)findViewById(R.id.text23);
        tx24=(TextView)findViewById(R.id.text24);
        tx25=(TextView)findViewById(R.id.text25);
        tx26=(TextView)findViewById(R.id.text26);
        tx27=(TextView)findViewById(R.id.text27);
        tx28=(TextView)findViewById(R.id.text28);
        tx29=(TextView)findViewById(R.id.text29);
        tx30=(TextView)findViewById(R.id.text30);
        tx31=(TextView)findViewById(R.id.text31);
        tx32=(TextView)findViewById(R.id.text32);
        tx33=(TextView)findViewById(R.id.text33);
        tx34=(TextView)findViewById(R.id.text34);
        tx35=(TextView)findViewById(R.id.text35);
        tx36=(TextView)findViewById(R.id.text36);
        tx37=(TextView)findViewById(R.id.text37);
        tx38=(TextView)findViewById(R.id.text38);
        tx39=(TextView)findViewById(R.id.text39);
        tx40=(TextView)findViewById(R.id.text40);
        tx41=(TextView)findViewById(R.id.text41);
        tx42=(TextView)findViewById(R.id.text42);
        tx43=(TextView)findViewById(R.id.text43);
      //  tx44=(TextView)findViewById(R.id.text44);
        tx45=(TextView)findViewById(R.id.text45);
        tx46=(TextView)findViewById(R.id.text46);
        tx47=(TextView)findViewById(R.id.text47);
        tx48=(TextView)findViewById(R.id.text48);
        tx49=(TextView)findViewById(R.id.text49);
        tx50=(TextView)findViewById(R.id.text50);
        tx51=(TextView)findViewById(R.id.text51);
        tx52=(TextView)findViewById(R.id.text52);
        tx53=(TextView)findViewById(R.id.text53);
        tx54=(TextView)findViewById(R.id.text54);
        tx55=(TextView)findViewById(R.id.text55);
        tx56=(TextView)findViewById(R.id.text56);
        tx57=(TextView)findViewById(R.id.text57);
        tx58=(TextView)findViewById(R.id.text58);
        tx59=(TextView)findViewById(R.id.text59);
        tx60=(TextView)findViewById(R.id.text60);

        tx1.setTypeface(tf1);
        tx2.setTypeface(tf1);
        tx3.setTypeface(tf1);
        tx4.setTypeface(tf1);
        tx5.setTypeface(tf1);
        tx6.setTypeface(tf1);
        tx7.setTypeface(tf1);
        tx8.setTypeface(tf1);
        tx9.setTypeface(tf1);
        tx10.setTypeface(tf1);
        tx11.setTypeface(tf1);
        tx12.setTypeface(tf1);
        tx13.setTypeface(tf1);
        tx14.setTypeface(tf1);
        tx15.setTypeface(tf1);
        tx16.setTypeface(tf1);
        tx17.setTypeface(tf1);
        tx18.setTypeface(tf1);
        tx19.setTypeface(tf1);
        tx20.setTypeface(tf1);
        tx21.setTypeface(tf1);
        tx22.setTypeface(tf1);
        tx23.setTypeface(tf1);
        tx24.setTypeface(tf1);
        tx25.setTypeface(tf1);
        tx26.setTypeface(tf1);
        tx27.setTypeface(tf1);
        tx28.setTypeface(tf1);
        tx29.setTypeface(tf1);
        tx30.setTypeface(tf1);
        tx31.setTypeface(tf1);
        tx32.setTypeface(tf1);
        tx33.setTypeface(tf1);
        tx34.setTypeface(tf1);
        tx35.setTypeface(tf1);
        tx36.setTypeface(tf1);
        tx37.setTypeface(tf1);
        tx38.setTypeface(tf1);
        tx39.setTypeface(tf1);
        tx40.setTypeface(tf1);
        tx41.setTypeface(tf1);
        tx42.setTypeface(tf1);
        tx43.setTypeface(tf1);
//        tx44.setTypeface(tf1);
        tx45.setTypeface(tf1);
        tx46.setTypeface(tf1);
        tx47.setTypeface(tf1);
        tx48.setTypeface(tf1);
        tx49.setTypeface(tf1);
        tx50.setTypeface(tf1);
        tx51.setTypeface(tf1);
        tx52.setTypeface(tf1);
        tx53.setTypeface(tf1);
        tx54.setTypeface(tf1);
        tx55.setTypeface(tf1);
        tx56.setTypeface(tf1);
        tx57.setTypeface(tf1);
        tx58.setTypeface(tf1);
        tx59.setTypeface(tf1);
        tx60.setTypeface(tf1);
    }
}
